set_property SRC_FILE_INFO {cfile:/home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0.xdc rfile:../tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0.xdc id:1 order:EARLY scoped_inst:trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc rfile:../tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc id:2 order:EARLY scoped_inst:clocking_wizard/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_example_design.xdc rfile:../imports/tri_mode_ethernet_mac_0_example_design.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_user_phytiming.xdc rfile:../imports/tri_mode_ethernet_mac_0_user_phytiming.xdc id:4 order:LATE} [current_design]
set_property SRC_FILE_INFO {cfile:/home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_clocks.xdc rfile:../tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/tri_mode_ethernet_mac_0/synth/tri_mode_ethernet_mac_0_clocks.xdc id:5 order:LATE scoped_inst:trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst} [current_design]
current_instance trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/flow/rx_pause/pause*to_tx_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_0_core/flow/tx_pause/count_set*reg}] 32 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/flow/rx_pause/pause*to_tx_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_0_core/flow/tx_pause/pause_count*reg[*]}] 32 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/flow/rx_pause/pause_req_to_tx_int_reg}] -to [get_cells {tri_mode_ethernet_mac_0_core/flow/tx_pause/sync_good_rx/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/rd_data_ref_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/ip2bus_data_reg[*]}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {vector_decode_inst/inc_vector_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/general_statisic_control[*].general_statisics/sync_inc_vector/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {vector_decode_inst/inc_vector_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/frame_size_bin_control1[*].frame_size_stats1/sync_inc_vector/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {vector_decode_inst/inc_vector_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/frame_size_bin_control2[*].frame_size_stats2/sync_inc_vector/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/*/accumulator_gray_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/*/accum_gray_resync[*].sync_accum_gray_i/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/response_toggle_reg}] -to [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/sync_response/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/request_toggle_reg}] -to [get_cells {tri_mode_ethernet_mac_0_core/*statistics_counters/sync_request/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/addr_filter_top/addr_regs.promiscuous_mode_reg_reg}] -to [get_cells {tri_mode_ethernet_mac_0_core/addr_filter_top/address_filter_inst/resync_promiscuous_mode/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/addr_filter_top/addr_regs.filter_enable_reg_reg[*]}] -to [get_cells {tri_mode_ethernet_mac_0_core/addr_filter_top/address_filter_inst/address_filters[*].sync_enable/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {tri_mode_ethernet_mac_0_core/*managen/conf/update_pause_ad_int_reg}] -to [get_cells {tri_mode_ethernet_mac_0_core/addr_filter_top/address_filter_inst/sync_update/data_sync_reg0}] 6 -datapath_only
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path 9 -hold -from   [get_cells {tri_mode_ethernet_mac_0_core/*managen/mdio_enabled.miim_clk_int_reg}  ] -throu [get_ports mdc]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path 9 -hold -from   [get_cells {tri_mode_ethernet_mac_0_core/*managen/mdio_enabled.phy/enable_reg_reg}] -throu [get_ports mdc]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path 9 -hold -from   [get_cells {tri_mode_ethernet_mac_0_core/*managen/mdio_enabled.phy/mdio*reg}      ] -throu [get_ports mdio]
current_instance
current_instance clocking_wizard/inst
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
current_instance
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells tx_stats_toggle_reg] -to [get_cells tx_stats_sync/data_sync_reg0] 6.000
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells rx_stats_toggle_reg] -to [get_cells rx_stats_sync/data_sync_reg0] 6.000
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/rd_addr_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 3.200
set_property src_info {type:XDC file:3 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/wr_store_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *fifo_i/resync_wr_store_frame_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:3 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/update_addr_tog_reg}] -to [get_cells -hier -filter {name =~ *rx_fifo_i/sync_rd_addr_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_addr_txfer_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 3.200
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frame_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frame_in_fifo/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frames_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frames_in_fifo/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/frame_in_fifo_valid_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_fif_valid_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_txfer_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_txfer_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_tran_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_tran_frame_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_power_opt -exclude_cells [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ *.bram.* }]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list ip_layer_inst/rx/n_0_5_BUFG]]
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clocking_wizard/inst/clk_out1]]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {ip_layer_inst/tx/nextstate[0]} {ip_layer_inst/tx/nextstate[1]} {ip_layer_inst/tx/nextstate[2]} {ip_layer_inst/tx/nextstate[3]} {ip_layer_inst/tx/nextstate[4]} {ip_layer_inst/tx/nextstate[5]} {ip_layer_inst/tx/nextstate[6]} {ip_layer_inst/tx/nextstate[7]}]]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {ip_layer_inst/tx/state[0]} {ip_layer_inst/tx/state[1]} {ip_layer_inst/tx/state[2]} {ip_layer_inst/tx/state[3]} {ip_layer_inst/tx/state[4]} {ip_layer_inst/tx/state[5]} {ip_layer_inst/tx/state[6]} {ip_layer_inst/tx/state[7]}]]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:4 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {tx_axis_fifo_tdata[0]} {tx_axis_fifo_tdata[1]} {tx_axis_fifo_tdata[2]} {tx_axis_fifo_tdata[3]} {tx_axis_fifo_tdata[4]} {tx_axis_fifo_tdata[5]} {tx_axis_fifo_tdata[6]} {tx_axis_fifo_tdata[7]}]]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {recipient_message_to_tx[0]} {recipient_message_to_tx[1]} {recipient_message_to_tx[2]} {recipient_message_to_tx[3]} {recipient_message_to_tx[4]} {recipient_message_to_tx[5]} {recipient_message_to_tx[6]} {recipient_message_to_tx[7]} {recipient_message_to_tx[8]} {recipient_message_to_tx[9]}]]
set_property src_info {type:XDC file:4 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:4 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {rx_axis_fifo_tdata[0]} {rx_axis_fifo_tdata[1]} {rx_axis_fifo_tdata[2]} {rx_axis_fifo_tdata[3]} {rx_axis_fifo_tdata[4]} {rx_axis_fifo_tdata[5]} {rx_axis_fifo_tdata[6]} {rx_axis_fifo_tdata[7]}]]
set_property src_info {type:XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 48 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {ip_layer_inst/rx/dst_mac_address[0]} {ip_layer_inst/rx/dst_mac_address[1]} {ip_layer_inst/rx/dst_mac_address[2]} {ip_layer_inst/rx/dst_mac_address[3]} {ip_layer_inst/rx/dst_mac_address[4]} {ip_layer_inst/rx/dst_mac_address[5]} {ip_layer_inst/rx/dst_mac_address[6]} {ip_layer_inst/rx/dst_mac_address[7]} {ip_layer_inst/rx/dst_mac_address[8]} {ip_layer_inst/rx/dst_mac_address[9]} {ip_layer_inst/rx/dst_mac_address[10]} {ip_layer_inst/rx/dst_mac_address[11]} {ip_layer_inst/rx/dst_mac_address[12]} {ip_layer_inst/rx/dst_mac_address[13]} {ip_layer_inst/rx/dst_mac_address[14]} {ip_layer_inst/rx/dst_mac_address[15]} {ip_layer_inst/rx/dst_mac_address[16]} {ip_layer_inst/rx/dst_mac_address[17]} {ip_layer_inst/rx/dst_mac_address[18]} {ip_layer_inst/rx/dst_mac_address[19]} {ip_layer_inst/rx/dst_mac_address[20]} {ip_layer_inst/rx/dst_mac_address[21]} {ip_layer_inst/rx/dst_mac_address[22]} {ip_layer_inst/rx/dst_mac_address[23]} {ip_layer_inst/rx/dst_mac_address[24]} {ip_layer_inst/rx/dst_mac_address[25]} {ip_layer_inst/rx/dst_mac_address[26]} {ip_layer_inst/rx/dst_mac_address[27]} {ip_layer_inst/rx/dst_mac_address[28]} {ip_layer_inst/rx/dst_mac_address[29]} {ip_layer_inst/rx/dst_mac_address[30]} {ip_layer_inst/rx/dst_mac_address[31]} {ip_layer_inst/rx/dst_mac_address[32]} {ip_layer_inst/rx/dst_mac_address[33]} {ip_layer_inst/rx/dst_mac_address[34]} {ip_layer_inst/rx/dst_mac_address[35]} {ip_layer_inst/rx/dst_mac_address[36]} {ip_layer_inst/rx/dst_mac_address[37]} {ip_layer_inst/rx/dst_mac_address[38]} {ip_layer_inst/rx/dst_mac_address[39]} {ip_layer_inst/rx/dst_mac_address[40]} {ip_layer_inst/rx/dst_mac_address[41]} {ip_layer_inst/rx/dst_mac_address[42]} {ip_layer_inst/rx/dst_mac_address[43]} {ip_layer_inst/rx/dst_mac_address[44]} {ip_layer_inst/rx/dst_mac_address[45]} {ip_layer_inst/rx/dst_mac_address[46]} {ip_layer_inst/rx/dst_mac_address[47]}]]
set_property src_info {type:XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:4 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {ip_layer_inst/rx/dst_ip_address[0]} {ip_layer_inst/rx/dst_ip_address[1]} {ip_layer_inst/rx/dst_ip_address[2]} {ip_layer_inst/rx/dst_ip_address[3]} {ip_layer_inst/rx/dst_ip_address[4]} {ip_layer_inst/rx/dst_ip_address[5]} {ip_layer_inst/rx/dst_ip_address[6]} {ip_layer_inst/rx/dst_ip_address[7]} {ip_layer_inst/rx/dst_ip_address[8]} {ip_layer_inst/rx/dst_ip_address[9]} {ip_layer_inst/rx/dst_ip_address[10]} {ip_layer_inst/rx/dst_ip_address[11]} {ip_layer_inst/rx/dst_ip_address[12]} {ip_layer_inst/rx/dst_ip_address[13]} {ip_layer_inst/rx/dst_ip_address[14]} {ip_layer_inst/rx/dst_ip_address[15]} {ip_layer_inst/rx/dst_ip_address[16]} {ip_layer_inst/rx/dst_ip_address[17]} {ip_layer_inst/rx/dst_ip_address[18]} {ip_layer_inst/rx/dst_ip_address[19]} {ip_layer_inst/rx/dst_ip_address[20]} {ip_layer_inst/rx/dst_ip_address[21]} {ip_layer_inst/rx/dst_ip_address[22]} {ip_layer_inst/rx/dst_ip_address[23]} {ip_layer_inst/rx/dst_ip_address[24]} {ip_layer_inst/rx/dst_ip_address[25]} {ip_layer_inst/rx/dst_ip_address[26]} {ip_layer_inst/rx/dst_ip_address[27]} {ip_layer_inst/rx/dst_ip_address[28]} {ip_layer_inst/rx/dst_ip_address[29]} {ip_layer_inst/rx/dst_ip_address[30]} {ip_layer_inst/rx/dst_ip_address[31]}]]
set_property src_info {type:XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {ip_layer_inst/rx/nextstate[0]} {ip_layer_inst/rx/nextstate[1]} {ip_layer_inst/rx/nextstate[2]} {ip_layer_inst/rx/nextstate[3]} {ip_layer_inst/rx/nextstate[4]} {ip_layer_inst/rx/nextstate[5]} {ip_layer_inst/rx/nextstate[6]} {ip_layer_inst/rx/nextstate[7]}]]
set_property src_info {type:XDC file:4 line:62 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:4 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:4 line:65 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {ip_layer_inst/rx/eth_header_data[0]} {ip_layer_inst/rx/eth_header_data[1]} {ip_layer_inst/rx/eth_header_data[2]} {ip_layer_inst/rx/eth_header_data[3]} {ip_layer_inst/rx/eth_header_data[4]} {ip_layer_inst/rx/eth_header_data[5]} {ip_layer_inst/rx/eth_header_data[6]} {ip_layer_inst/rx/eth_header_data[7]} {ip_layer_inst/rx/eth_header_data[8]} {ip_layer_inst/rx/eth_header_data[9]} {ip_layer_inst/rx/eth_header_data[10]} {ip_layer_inst/rx/eth_header_data[11]} {ip_layer_inst/rx/eth_header_data[12]} {ip_layer_inst/rx/eth_header_data[13]} {ip_layer_inst/rx/eth_header_data[14]} {ip_layer_inst/rx/eth_header_data[15]} {ip_layer_inst/rx/eth_header_data[16]} {ip_layer_inst/rx/eth_header_data[17]} {ip_layer_inst/rx/eth_header_data[18]} {ip_layer_inst/rx/eth_header_data[19]} {ip_layer_inst/rx/eth_header_data[20]} {ip_layer_inst/rx/eth_header_data[21]} {ip_layer_inst/rx/eth_header_data[22]} {ip_layer_inst/rx/eth_header_data[23]} {ip_layer_inst/rx/eth_header_data[24]} {ip_layer_inst/rx/eth_header_data[25]} {ip_layer_inst/rx/eth_header_data[26]} {ip_layer_inst/rx/eth_header_data[27]} {ip_layer_inst/rx/eth_header_data[28]} {ip_layer_inst/rx/eth_header_data[29]} {ip_layer_inst/rx/eth_header_data[30]} {ip_layer_inst/rx/eth_header_data[31]} {ip_layer_inst/rx/eth_header_data[32]} {ip_layer_inst/rx/eth_header_data[33]} {ip_layer_inst/rx/eth_header_data[34]} {ip_layer_inst/rx/eth_header_data[35]} {ip_layer_inst/rx/eth_header_data[36]} {ip_layer_inst/rx/eth_header_data[37]} {ip_layer_inst/rx/eth_header_data[38]} {ip_layer_inst/rx/eth_header_data[39]} {ip_layer_inst/rx/eth_header_data[40]} {ip_layer_inst/rx/eth_header_data[41]} {ip_layer_inst/rx/eth_header_data[42]} {ip_layer_inst/rx/eth_header_data[43]} {ip_layer_inst/rx/eth_header_data[44]} {ip_layer_inst/rx/eth_header_data[45]} {ip_layer_inst/rx/eth_header_data[46]} {ip_layer_inst/rx/eth_header_data[47]} {ip_layer_inst/rx/eth_header_data[96]} {ip_layer_inst/rx/eth_header_data[97]} {ip_layer_inst/rx/eth_header_data[98]} {ip_layer_inst/rx/eth_header_data[99]} {ip_layer_inst/rx/eth_header_data[100]} {ip_layer_inst/rx/eth_header_data[101]} {ip_layer_inst/rx/eth_header_data[102]} {ip_layer_inst/rx/eth_header_data[103]} {ip_layer_inst/rx/eth_header_data[104]} {ip_layer_inst/rx/eth_header_data[105]} {ip_layer_inst/rx/eth_header_data[106]} {ip_layer_inst/rx/eth_header_data[107]} {ip_layer_inst/rx/eth_header_data[108]} {ip_layer_inst/rx/eth_header_data[109]} {ip_layer_inst/rx/eth_header_data[110]} {ip_layer_inst/rx/eth_header_data[111]}]]
set_property src_info {type:XDC file:4 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 128 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:4 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {ip_layer_inst/rx/ip_header_data[0]} {ip_layer_inst/rx/ip_header_data[1]} {ip_layer_inst/rx/ip_header_data[2]} {ip_layer_inst/rx/ip_header_data[3]} {ip_layer_inst/rx/ip_header_data[4]} {ip_layer_inst/rx/ip_header_data[5]} {ip_layer_inst/rx/ip_header_data[6]} {ip_layer_inst/rx/ip_header_data[7]} {ip_layer_inst/rx/ip_header_data[8]} {ip_layer_inst/rx/ip_header_data[9]} {ip_layer_inst/rx/ip_header_data[10]} {ip_layer_inst/rx/ip_header_data[11]} {ip_layer_inst/rx/ip_header_data[12]} {ip_layer_inst/rx/ip_header_data[13]} {ip_layer_inst/rx/ip_header_data[14]} {ip_layer_inst/rx/ip_header_data[15]} {ip_layer_inst/rx/ip_header_data[16]} {ip_layer_inst/rx/ip_header_data[17]} {ip_layer_inst/rx/ip_header_data[18]} {ip_layer_inst/rx/ip_header_data[19]} {ip_layer_inst/rx/ip_header_data[20]} {ip_layer_inst/rx/ip_header_data[21]} {ip_layer_inst/rx/ip_header_data[22]} {ip_layer_inst/rx/ip_header_data[23]} {ip_layer_inst/rx/ip_header_data[24]} {ip_layer_inst/rx/ip_header_data[25]} {ip_layer_inst/rx/ip_header_data[26]} {ip_layer_inst/rx/ip_header_data[27]} {ip_layer_inst/rx/ip_header_data[28]} {ip_layer_inst/rx/ip_header_data[29]} {ip_layer_inst/rx/ip_header_data[30]} {ip_layer_inst/rx/ip_header_data[31]} {ip_layer_inst/rx/ip_header_data[32]} {ip_layer_inst/rx/ip_header_data[33]} {ip_layer_inst/rx/ip_header_data[34]} {ip_layer_inst/rx/ip_header_data[35]} {ip_layer_inst/rx/ip_header_data[36]} {ip_layer_inst/rx/ip_header_data[37]} {ip_layer_inst/rx/ip_header_data[38]} {ip_layer_inst/rx/ip_header_data[39]} {ip_layer_inst/rx/ip_header_data[40]} {ip_layer_inst/rx/ip_header_data[41]} {ip_layer_inst/rx/ip_header_data[42]} {ip_layer_inst/rx/ip_header_data[43]} {ip_layer_inst/rx/ip_header_data[44]} {ip_layer_inst/rx/ip_header_data[45]} {ip_layer_inst/rx/ip_header_data[46]} {ip_layer_inst/rx/ip_header_data[47]} {ip_layer_inst/rx/ip_header_data[48]} {ip_layer_inst/rx/ip_header_data[49]} {ip_layer_inst/rx/ip_header_data[50]} {ip_layer_inst/rx/ip_header_data[51]} {ip_layer_inst/rx/ip_header_data[52]} {ip_layer_inst/rx/ip_header_data[53]} {ip_layer_inst/rx/ip_header_data[54]} {ip_layer_inst/rx/ip_header_data[55]} {ip_layer_inst/rx/ip_header_data[56]} {ip_layer_inst/rx/ip_header_data[57]} {ip_layer_inst/rx/ip_header_data[58]} {ip_layer_inst/rx/ip_header_data[59]} {ip_layer_inst/rx/ip_header_data[60]} {ip_layer_inst/rx/ip_header_data[61]} {ip_layer_inst/rx/ip_header_data[62]} {ip_layer_inst/rx/ip_header_data[63]} {ip_layer_inst/rx/ip_header_data[64]} {ip_layer_inst/rx/ip_header_data[65]} {ip_layer_inst/rx/ip_header_data[66]} {ip_layer_inst/rx/ip_header_data[67]} {ip_layer_inst/rx/ip_header_data[68]} {ip_layer_inst/rx/ip_header_data[69]} {ip_layer_inst/rx/ip_header_data[70]} {ip_layer_inst/rx/ip_header_data[71]} {ip_layer_inst/rx/ip_header_data[72]} {ip_layer_inst/rx/ip_header_data[73]} {ip_layer_inst/rx/ip_header_data[74]} {ip_layer_inst/rx/ip_header_data[75]} {ip_layer_inst/rx/ip_header_data[76]} {ip_layer_inst/rx/ip_header_data[77]} {ip_layer_inst/rx/ip_header_data[78]} {ip_layer_inst/rx/ip_header_data[79]} {ip_layer_inst/rx/ip_header_data[80]} {ip_layer_inst/rx/ip_header_data[81]} {ip_layer_inst/rx/ip_header_data[82]} {ip_layer_inst/rx/ip_header_data[83]} {ip_layer_inst/rx/ip_header_data[84]} {ip_layer_inst/rx/ip_header_data[85]} {ip_layer_inst/rx/ip_header_data[86]} {ip_layer_inst/rx/ip_header_data[87]} {ip_layer_inst/rx/ip_header_data[88]} {ip_layer_inst/rx/ip_header_data[89]} {ip_layer_inst/rx/ip_header_data[90]} {ip_layer_inst/rx/ip_header_data[91]} {ip_layer_inst/rx/ip_header_data[92]} {ip_layer_inst/rx/ip_header_data[93]} {ip_layer_inst/rx/ip_header_data[94]} {ip_layer_inst/rx/ip_header_data[95]} {ip_layer_inst/rx/ip_header_data[128]} {ip_layer_inst/rx/ip_header_data[129]} {ip_layer_inst/rx/ip_header_data[130]} {ip_layer_inst/rx/ip_header_data[131]} {ip_layer_inst/rx/ip_header_data[132]} {ip_layer_inst/rx/ip_header_data[133]} {ip_layer_inst/rx/ip_header_data[134]} {ip_layer_inst/rx/ip_header_data[135]} {ip_layer_inst/rx/ip_header_data[136]} {ip_layer_inst/rx/ip_header_data[137]} {ip_layer_inst/rx/ip_header_data[138]} {ip_layer_inst/rx/ip_header_data[139]} {ip_layer_inst/rx/ip_header_data[140]} {ip_layer_inst/rx/ip_header_data[141]} {ip_layer_inst/rx/ip_header_data[142]} {ip_layer_inst/rx/ip_header_data[143]} {ip_layer_inst/rx/ip_header_data[144]} {ip_layer_inst/rx/ip_header_data[145]} {ip_layer_inst/rx/ip_header_data[146]} {ip_layer_inst/rx/ip_header_data[147]} {ip_layer_inst/rx/ip_header_data[148]} {ip_layer_inst/rx/ip_header_data[149]} {ip_layer_inst/rx/ip_header_data[150]} {ip_layer_inst/rx/ip_header_data[151]} {ip_layer_inst/rx/ip_header_data[152]} {ip_layer_inst/rx/ip_header_data[153]} {ip_layer_inst/rx/ip_header_data[154]} {ip_layer_inst/rx/ip_header_data[155]} {ip_layer_inst/rx/ip_header_data[156]} {ip_layer_inst/rx/ip_header_data[157]} {ip_layer_inst/rx/ip_header_data[158]} {ip_layer_inst/rx/ip_header_data[159]}]]
set_property src_info {type:XDC file:4 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:4 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:4 line:73 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {ip_layer_inst/rx/state[0]} {ip_layer_inst/rx/state[1]} {ip_layer_inst/rx/state[2]} {ip_layer_inst/rx/state[3]} {ip_layer_inst/rx/state[4]} {ip_layer_inst/rx/state[5]} {ip_layer_inst/rx/state[6]} {ip_layer_inst/rx/state[7]}]]
set_property src_info {type:XDC file:4 line:74 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:4 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {ip_layer_inst/rx/state_counter[0]} {ip_layer_inst/rx/state_counter[1]} {ip_layer_inst/rx/state_counter[2]} {ip_layer_inst/rx/state_counter[3]} {ip_layer_inst/rx/state_counter[4]} {ip_layer_inst/rx/state_counter[5]} {ip_layer_inst/rx/state_counter[6]} {ip_layer_inst/rx/state_counter[7]} {ip_layer_inst/rx/state_counter[8]} {ip_layer_inst/rx/state_counter[9]} {ip_layer_inst/rx/state_counter[10]} {ip_layer_inst/rx/state_counter[11]} {ip_layer_inst/rx/state_counter[12]} {ip_layer_inst/rx/state_counter[13]} {ip_layer_inst/rx/state_counter[14]} {ip_layer_inst/rx/state_counter[15]}]]
set_property src_info {type:XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:4 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:4 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {ip_address_from_rx[0]} {ip_address_from_rx[1]} {ip_address_from_rx[2]} {ip_address_from_rx[3]} {ip_address_from_rx[4]} {ip_address_from_rx[5]} {ip_address_from_rx[6]} {ip_address_from_rx[7]} {ip_address_from_rx[8]} {ip_address_from_rx[9]} {ip_address_from_rx[10]} {ip_address_from_rx[11]} {ip_address_from_rx[12]} {ip_address_from_rx[13]} {ip_address_from_rx[14]} {ip_address_from_rx[15]} {ip_address_from_rx[16]} {ip_address_from_rx[17]} {ip_address_from_rx[18]} {ip_address_from_rx[19]} {ip_address_from_rx[20]} {ip_address_from_rx[21]} {ip_address_from_rx[22]} {ip_address_from_rx[23]} {ip_address_from_rx[24]} {ip_address_from_rx[25]} {ip_address_from_rx[26]} {ip_address_from_rx[27]} {ip_address_from_rx[28]} {ip_address_from_rx[29]} {ip_address_from_rx[30]} {ip_address_from_rx[31]}]]
set_property src_info {type:XDC file:4 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:4 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 48 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:4 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {mac_address_from_rx[0]} {mac_address_from_rx[1]} {mac_address_from_rx[2]} {mac_address_from_rx[3]} {mac_address_from_rx[4]} {mac_address_from_rx[5]} {mac_address_from_rx[6]} {mac_address_from_rx[7]} {mac_address_from_rx[8]} {mac_address_from_rx[9]} {mac_address_from_rx[10]} {mac_address_from_rx[11]} {mac_address_from_rx[12]} {mac_address_from_rx[13]} {mac_address_from_rx[14]} {mac_address_from_rx[15]} {mac_address_from_rx[16]} {mac_address_from_rx[17]} {mac_address_from_rx[18]} {mac_address_from_rx[19]} {mac_address_from_rx[20]} {mac_address_from_rx[21]} {mac_address_from_rx[22]} {mac_address_from_rx[23]} {mac_address_from_rx[24]} {mac_address_from_rx[25]} {mac_address_from_rx[26]} {mac_address_from_rx[27]} {mac_address_from_rx[28]} {mac_address_from_rx[29]} {mac_address_from_rx[30]} {mac_address_from_rx[31]} {mac_address_from_rx[32]} {mac_address_from_rx[33]} {mac_address_from_rx[34]} {mac_address_from_rx[35]} {mac_address_from_rx[36]} {mac_address_from_rx[37]} {mac_address_from_rx[38]} {mac_address_from_rx[39]} {mac_address_from_rx[40]} {mac_address_from_rx[41]} {mac_address_from_rx[42]} {mac_address_from_rx[43]} {mac_address_from_rx[44]} {mac_address_from_rx[45]} {mac_address_from_rx[46]} {mac_address_from_rx[47]}]]
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:4 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list ip_layer_inst/rx/data_frame_enable]]
set_property src_info {type:XDC file:4 line:90 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:4 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:4 line:93 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list ip_layer_inst/rx/eth_header_enable]]
set_property src_info {type:XDC file:4 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:4 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:4 line:97 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list frame_ready_from_rx]]
set_property src_info {type:XDC file:4 line:98 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:4 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:4 line:101 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list ip_layer_inst/rx/ip_header_enable]]
set_property src_info {type:XDC file:4 line:102 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:4 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:4 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list ready_for_send_to_tx]]
set_property src_info {type:XDC file:4 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:4 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:4 line:109 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list rx_axis_fifo_tlast]]
set_property src_info {type:XDC file:4 line:110 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:4 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:4 line:113 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list rx_axis_fifo_tvalid]]
set_property src_info {type:XDC file:4 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:4 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:4 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list start_ip_txn_to_tx]]
set_property src_info {type:XDC file:4 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:4 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:4 line:121 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list ip_layer_inst/rx/state_counter_enable]]
set_property src_info {type:XDC file:4 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:4 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:4 line:125 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list ip_layer_inst/rx/state_counter_reset]]
set_property src_info {type:XDC file:4 line:126 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:4 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:4 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list tx_axis_fifo_tlast]]
set_property src_info {type:XDC file:4 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:4 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:4 line:133 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list tx_axis_fifo_tready]]
set_property src_info {type:XDC file:4 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:4 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:4 line:137 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list tx_axis_fifo_tvalid]]
set_property src_info {type:XDC file:4 line:138 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:4 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:4 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:4 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:4 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:4 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:4 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:4 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:4 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:4 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:4 line:148 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list clocking_wizard/inst/clk_out2]]
set_property src_info {type:XDC file:4 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:4 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:4 line:151 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {mii_rxd[0]} {mii_rxd[1]} {mii_rxd[2]} {mii_rxd[3]}]]
set_property src_info {type:XDC file:4 line:152 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:4 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:4 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:4 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list {phy2rmii_rxd_IBUF[0]} {phy2rmii_rxd_IBUF[1]}]]
set_property src_info {type:XDC file:4 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:159 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets sys_clk_IBUF]
current_instance trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst
set_property src_info {type:SCOPED_XDC file:5 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks -of_objects [get_pins trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst/mii_rx_clk]] -max 30            [get_ports {mii_rxd[*] mii_rx_er mii_rx_dv}]
set_property src_info {type:SCOPED_XDC file:5 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks -of_objects [get_pins trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst/mii_rx_clk]] -min 10 -add_delay [get_ports {mii_rxd[*] mii_rx_er mii_rx_dv}]
set_property src_info {type:SCOPED_XDC file:5 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells {axi4_lite_ipif/axi4_lite_ipif_top_wrapper/axi_lite_top/*/bus2ip_addr_i_reg[*]}] -to [get_clocks -of_objects [get_pins trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst/gtx_clk]] 6 -datapath_only
