# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andrew/ECE532-sandbox/MNIST_Solver/MNIST_Solver.srcs/sources_1/ip/Mult_Add_Pipelined_NC/Mult_Add_Pipelined_NC.xci
# IP: The module: 'Mult_Add_Pipelined_NC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/ECE532-sandbox/MNIST_Solver/MNIST_Solver.srcs/sources_1/ip/Mult_Add_Pipelined_NC/Mult_Add_Pipelined_NC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mult_Add_Pipelined_NC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/andrew/ECE532-sandbox/MNIST_Solver/MNIST_Solver.srcs/sources_1/ip/Mult_Add_Pipelined_NC/Mult_Add_Pipelined_NC.xci
# IP: The module: 'Mult_Add_Pipelined_NC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/ECE532-sandbox/MNIST_Solver/MNIST_Solver.srcs/sources_1/ip/Mult_Add_Pipelined_NC/Mult_Add_Pipelined_NC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mult_Add_Pipelined_NC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
