set_property SRC_FILE_INFO {cfile:/home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_example_design.xdc rfile:../../../imports/tri_mode_ethernet_mac_0_example_design.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_user_phytiming.xdc rfile:../../../imports/tri_mode_ethernet_mac_0_user_phytiming.xdc id:2 order:LATE} [current_design]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33} [get_ports mdc]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports mdio]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports phy2rmii_crs_dv]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C10 IOSTANDARD LVCMOS33} [get_ports phy2rmii_rx_er]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports {phy2rmii_rxd[0]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports {phy2rmii_rxd[1]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33} [get_ports rmii2phy_tx_en]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33} [get_ports {rmii2phy_txd[0]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS33} [get_ports {rmii2phy_txd[1]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports rmii2phy_refclk]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells tx_stats_toggle_reg] -to [get_cells tx_stats_sync/data_sync_reg0] 6.000
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells rx_stats_toggle_reg] -to [get_cells rx_stats_sync/data_sync_reg0] 6.000
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/rd_addr_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 3.200
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/wr_store_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *fifo_i/resync_wr_store_frame_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/update_addr_tog_reg}] -to [get_cells -hier -filter {name =~ *rx_fifo_i/sync_rd_addr_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_addr_txfer_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 3.200
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frame_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frame_in_fifo/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frames_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frames_in_fifo/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/frame_in_fifo_valid_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_fif_valid_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_txfer_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_txfer_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_tran_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_tran_frame_tog/data_sync_reg0}] 3.200
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_power_opt -exclude_cells [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ *.bram.* }]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list ip_layer_inst/rx/n_0_5_BUFG]]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clocking_wizard/inst/clk_out1]]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 48 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {ip_layer_inst/rx/dst_mac_address[47]} {ip_layer_inst/rx/dst_mac_address[46]} {ip_layer_inst/rx/dst_mac_address[45]} {ip_layer_inst/rx/dst_mac_address[44]} {ip_layer_inst/rx/dst_mac_address[43]} {ip_layer_inst/rx/dst_mac_address[42]} {ip_layer_inst/rx/dst_mac_address[41]} {ip_layer_inst/rx/dst_mac_address[40]} {ip_layer_inst/rx/dst_mac_address[39]} {ip_layer_inst/rx/dst_mac_address[38]} {ip_layer_inst/rx/dst_mac_address[37]} {ip_layer_inst/rx/dst_mac_address[36]} {ip_layer_inst/rx/dst_mac_address[35]} {ip_layer_inst/rx/dst_mac_address[34]} {ip_layer_inst/rx/dst_mac_address[33]} {ip_layer_inst/rx/dst_mac_address[32]} {ip_layer_inst/rx/dst_mac_address[31]} {ip_layer_inst/rx/dst_mac_address[30]} {ip_layer_inst/rx/dst_mac_address[29]} {ip_layer_inst/rx/dst_mac_address[28]} {ip_layer_inst/rx/dst_mac_address[27]} {ip_layer_inst/rx/dst_mac_address[26]} {ip_layer_inst/rx/dst_mac_address[25]} {ip_layer_inst/rx/dst_mac_address[24]} {ip_layer_inst/rx/dst_mac_address[23]} {ip_layer_inst/rx/dst_mac_address[22]} {ip_layer_inst/rx/dst_mac_address[21]} {ip_layer_inst/rx/dst_mac_address[20]} {ip_layer_inst/rx/dst_mac_address[19]} {ip_layer_inst/rx/dst_mac_address[18]} {ip_layer_inst/rx/dst_mac_address[17]} {ip_layer_inst/rx/dst_mac_address[16]} {ip_layer_inst/rx/dst_mac_address[15]} {ip_layer_inst/rx/dst_mac_address[14]} {ip_layer_inst/rx/dst_mac_address[13]} {ip_layer_inst/rx/dst_mac_address[12]} {ip_layer_inst/rx/dst_mac_address[11]} {ip_layer_inst/rx/dst_mac_address[10]} {ip_layer_inst/rx/dst_mac_address[9]} {ip_layer_inst/rx/dst_mac_address[8]} {ip_layer_inst/rx/dst_mac_address[7]} {ip_layer_inst/rx/dst_mac_address[6]} {ip_layer_inst/rx/dst_mac_address[5]} {ip_layer_inst/rx/dst_mac_address[4]} {ip_layer_inst/rx/dst_mac_address[3]} {ip_layer_inst/rx/dst_mac_address[2]} {ip_layer_inst/rx/dst_mac_address[1]} {ip_layer_inst/rx/dst_mac_address[0]}]]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 128 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {ip_layer_inst/rx/ip_header_data[159]} {ip_layer_inst/rx/ip_header_data[158]} {ip_layer_inst/rx/ip_header_data[157]} {ip_layer_inst/rx/ip_header_data[156]} {ip_layer_inst/rx/ip_header_data[155]} {ip_layer_inst/rx/ip_header_data[154]} {ip_layer_inst/rx/ip_header_data[153]} {ip_layer_inst/rx/ip_header_data[152]} {ip_layer_inst/rx/ip_header_data[151]} {ip_layer_inst/rx/ip_header_data[150]} {ip_layer_inst/rx/ip_header_data[149]} {ip_layer_inst/rx/ip_header_data[148]} {ip_layer_inst/rx/ip_header_data[147]} {ip_layer_inst/rx/ip_header_data[146]} {ip_layer_inst/rx/ip_header_data[145]} {ip_layer_inst/rx/ip_header_data[144]} {ip_layer_inst/rx/ip_header_data[143]} {ip_layer_inst/rx/ip_header_data[142]} {ip_layer_inst/rx/ip_header_data[141]} {ip_layer_inst/rx/ip_header_data[140]} {ip_layer_inst/rx/ip_header_data[139]} {ip_layer_inst/rx/ip_header_data[138]} {ip_layer_inst/rx/ip_header_data[137]} {ip_layer_inst/rx/ip_header_data[136]} {ip_layer_inst/rx/ip_header_data[135]} {ip_layer_inst/rx/ip_header_data[134]} {ip_layer_inst/rx/ip_header_data[133]} {ip_layer_inst/rx/ip_header_data[132]} {ip_layer_inst/rx/ip_header_data[131]} {ip_layer_inst/rx/ip_header_data[130]} {ip_layer_inst/rx/ip_header_data[129]} {ip_layer_inst/rx/ip_header_data[128]} {ip_layer_inst/rx/ip_header_data[95]} {ip_layer_inst/rx/ip_header_data[94]} {ip_layer_inst/rx/ip_header_data[93]} {ip_layer_inst/rx/ip_header_data[92]} {ip_layer_inst/rx/ip_header_data[91]} {ip_layer_inst/rx/ip_header_data[90]} {ip_layer_inst/rx/ip_header_data[89]} {ip_layer_inst/rx/ip_header_data[88]} {ip_layer_inst/rx/ip_header_data[87]} {ip_layer_inst/rx/ip_header_data[86]} {ip_layer_inst/rx/ip_header_data[85]} {ip_layer_inst/rx/ip_header_data[84]} {ip_layer_inst/rx/ip_header_data[83]} {ip_layer_inst/rx/ip_header_data[82]} {ip_layer_inst/rx/ip_header_data[81]} {ip_layer_inst/rx/ip_header_data[80]} {ip_layer_inst/rx/ip_header_data[79]} {ip_layer_inst/rx/ip_header_data[78]} {ip_layer_inst/rx/ip_header_data[77]} {ip_layer_inst/rx/ip_header_data[76]} {ip_layer_inst/rx/ip_header_data[75]} {ip_layer_inst/rx/ip_header_data[74]} {ip_layer_inst/rx/ip_header_data[73]} {ip_layer_inst/rx/ip_header_data[72]} {ip_layer_inst/rx/ip_header_data[71]} {ip_layer_inst/rx/ip_header_data[70]} {ip_layer_inst/rx/ip_header_data[69]} {ip_layer_inst/rx/ip_header_data[68]} {ip_layer_inst/rx/ip_header_data[67]} {ip_layer_inst/rx/ip_header_data[66]} {ip_layer_inst/rx/ip_header_data[65]} {ip_layer_inst/rx/ip_header_data[64]} {ip_layer_inst/rx/ip_header_data[63]} {ip_layer_inst/rx/ip_header_data[62]} {ip_layer_inst/rx/ip_header_data[61]} {ip_layer_inst/rx/ip_header_data[60]} {ip_layer_inst/rx/ip_header_data[59]} {ip_layer_inst/rx/ip_header_data[58]} {ip_layer_inst/rx/ip_header_data[57]} {ip_layer_inst/rx/ip_header_data[56]} {ip_layer_inst/rx/ip_header_data[55]} {ip_layer_inst/rx/ip_header_data[54]} {ip_layer_inst/rx/ip_header_data[53]} {ip_layer_inst/rx/ip_header_data[52]} {ip_layer_inst/rx/ip_header_data[51]} {ip_layer_inst/rx/ip_header_data[50]} {ip_layer_inst/rx/ip_header_data[49]} {ip_layer_inst/rx/ip_header_data[48]} {ip_layer_inst/rx/ip_header_data[47]} {ip_layer_inst/rx/ip_header_data[46]} {ip_layer_inst/rx/ip_header_data[45]} {ip_layer_inst/rx/ip_header_data[44]} {ip_layer_inst/rx/ip_header_data[43]} {ip_layer_inst/rx/ip_header_data[42]} {ip_layer_inst/rx/ip_header_data[41]} {ip_layer_inst/rx/ip_header_data[40]} {ip_layer_inst/rx/ip_header_data[39]} {ip_layer_inst/rx/ip_header_data[38]} {ip_layer_inst/rx/ip_header_data[37]} {ip_layer_inst/rx/ip_header_data[36]} {ip_layer_inst/rx/ip_header_data[35]} {ip_layer_inst/rx/ip_header_data[34]} {ip_layer_inst/rx/ip_header_data[33]} {ip_layer_inst/rx/ip_header_data[32]} {ip_layer_inst/rx/ip_header_data[31]} {ip_layer_inst/rx/ip_header_data[30]} {ip_layer_inst/rx/ip_header_data[29]} {ip_layer_inst/rx/ip_header_data[28]} {ip_layer_inst/rx/ip_header_data[27]} {ip_layer_inst/rx/ip_header_data[26]} {ip_layer_inst/rx/ip_header_data[25]} {ip_layer_inst/rx/ip_header_data[24]} {ip_layer_inst/rx/ip_header_data[23]} {ip_layer_inst/rx/ip_header_data[22]} {ip_layer_inst/rx/ip_header_data[21]} {ip_layer_inst/rx/ip_header_data[20]} {ip_layer_inst/rx/ip_header_data[19]} {ip_layer_inst/rx/ip_header_data[18]} {ip_layer_inst/rx/ip_header_data[17]} {ip_layer_inst/rx/ip_header_data[16]} {ip_layer_inst/rx/ip_header_data[15]} {ip_layer_inst/rx/ip_header_data[14]} {ip_layer_inst/rx/ip_header_data[13]} {ip_layer_inst/rx/ip_header_data[12]} {ip_layer_inst/rx/ip_header_data[11]} {ip_layer_inst/rx/ip_header_data[10]} {ip_layer_inst/rx/ip_header_data[9]} {ip_layer_inst/rx/ip_header_data[8]} {ip_layer_inst/rx/ip_header_data[7]} {ip_layer_inst/rx/ip_header_data[6]} {ip_layer_inst/rx/ip_header_data[5]} {ip_layer_inst/rx/ip_header_data[4]} {ip_layer_inst/rx/ip_header_data[3]} {ip_layer_inst/rx/ip_header_data[2]} {ip_layer_inst/rx/ip_header_data[1]} {ip_layer_inst/rx/ip_header_data[0]}]]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {ip_layer_inst/rx/dst_ip_address[31]} {ip_layer_inst/rx/dst_ip_address[30]} {ip_layer_inst/rx/dst_ip_address[29]} {ip_layer_inst/rx/dst_ip_address[28]} {ip_layer_inst/rx/dst_ip_address[27]} {ip_layer_inst/rx/dst_ip_address[26]} {ip_layer_inst/rx/dst_ip_address[25]} {ip_layer_inst/rx/dst_ip_address[24]} {ip_layer_inst/rx/dst_ip_address[23]} {ip_layer_inst/rx/dst_ip_address[22]} {ip_layer_inst/rx/dst_ip_address[21]} {ip_layer_inst/rx/dst_ip_address[20]} {ip_layer_inst/rx/dst_ip_address[19]} {ip_layer_inst/rx/dst_ip_address[18]} {ip_layer_inst/rx/dst_ip_address[17]} {ip_layer_inst/rx/dst_ip_address[16]} {ip_layer_inst/rx/dst_ip_address[15]} {ip_layer_inst/rx/dst_ip_address[14]} {ip_layer_inst/rx/dst_ip_address[13]} {ip_layer_inst/rx/dst_ip_address[12]} {ip_layer_inst/rx/dst_ip_address[11]} {ip_layer_inst/rx/dst_ip_address[10]} {ip_layer_inst/rx/dst_ip_address[9]} {ip_layer_inst/rx/dst_ip_address[8]} {ip_layer_inst/rx/dst_ip_address[7]} {ip_layer_inst/rx/dst_ip_address[6]} {ip_layer_inst/rx/dst_ip_address[5]} {ip_layer_inst/rx/dst_ip_address[4]} {ip_layer_inst/rx/dst_ip_address[3]} {ip_layer_inst/rx/dst_ip_address[2]} {ip_layer_inst/rx/dst_ip_address[1]} {ip_layer_inst/rx/dst_ip_address[0]}]]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {ip_layer_inst/rx/dst_udp_port[15]} {ip_layer_inst/rx/dst_udp_port[14]} {ip_layer_inst/rx/dst_udp_port[13]} {ip_layer_inst/rx/dst_udp_port[12]} {ip_layer_inst/rx/dst_udp_port[11]} {ip_layer_inst/rx/dst_udp_port[10]} {ip_layer_inst/rx/dst_udp_port[9]} {ip_layer_inst/rx/dst_udp_port[8]} {ip_layer_inst/rx/dst_udp_port[7]} {ip_layer_inst/rx/dst_udp_port[6]} {ip_layer_inst/rx/dst_udp_port[5]} {ip_layer_inst/rx/dst_udp_port[4]} {ip_layer_inst/rx/dst_udp_port[3]} {ip_layer_inst/rx/dst_udp_port[2]} {ip_layer_inst/rx/dst_udp_port[1]} {ip_layer_inst/rx/dst_udp_port[0]}]]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {ip_layer_inst/rx/eth_header_data[111]} {ip_layer_inst/rx/eth_header_data[110]} {ip_layer_inst/rx/eth_header_data[109]} {ip_layer_inst/rx/eth_header_data[108]} {ip_layer_inst/rx/eth_header_data[107]} {ip_layer_inst/rx/eth_header_data[106]} {ip_layer_inst/rx/eth_header_data[105]} {ip_layer_inst/rx/eth_header_data[104]} {ip_layer_inst/rx/eth_header_data[103]} {ip_layer_inst/rx/eth_header_data[102]} {ip_layer_inst/rx/eth_header_data[101]} {ip_layer_inst/rx/eth_header_data[100]} {ip_layer_inst/rx/eth_header_data[99]} {ip_layer_inst/rx/eth_header_data[98]} {ip_layer_inst/rx/eth_header_data[97]} {ip_layer_inst/rx/eth_header_data[96]} {ip_layer_inst/rx/eth_header_data[47]} {ip_layer_inst/rx/eth_header_data[46]} {ip_layer_inst/rx/eth_header_data[45]} {ip_layer_inst/rx/eth_header_data[44]} {ip_layer_inst/rx/eth_header_data[43]} {ip_layer_inst/rx/eth_header_data[42]} {ip_layer_inst/rx/eth_header_data[41]} {ip_layer_inst/rx/eth_header_data[40]} {ip_layer_inst/rx/eth_header_data[39]} {ip_layer_inst/rx/eth_header_data[38]} {ip_layer_inst/rx/eth_header_data[37]} {ip_layer_inst/rx/eth_header_data[36]} {ip_layer_inst/rx/eth_header_data[35]} {ip_layer_inst/rx/eth_header_data[34]} {ip_layer_inst/rx/eth_header_data[33]} {ip_layer_inst/rx/eth_header_data[32]} {ip_layer_inst/rx/eth_header_data[31]} {ip_layer_inst/rx/eth_header_data[30]} {ip_layer_inst/rx/eth_header_data[29]} {ip_layer_inst/rx/eth_header_data[28]} {ip_layer_inst/rx/eth_header_data[27]} {ip_layer_inst/rx/eth_header_data[26]} {ip_layer_inst/rx/eth_header_data[25]} {ip_layer_inst/rx/eth_header_data[24]} {ip_layer_inst/rx/eth_header_data[23]} {ip_layer_inst/rx/eth_header_data[22]} {ip_layer_inst/rx/eth_header_data[21]} {ip_layer_inst/rx/eth_header_data[20]} {ip_layer_inst/rx/eth_header_data[19]} {ip_layer_inst/rx/eth_header_data[18]} {ip_layer_inst/rx/eth_header_data[17]} {ip_layer_inst/rx/eth_header_data[16]} {ip_layer_inst/rx/eth_header_data[15]} {ip_layer_inst/rx/eth_header_data[14]} {ip_layer_inst/rx/eth_header_data[13]} {ip_layer_inst/rx/eth_header_data[12]} {ip_layer_inst/rx/eth_header_data[11]} {ip_layer_inst/rx/eth_header_data[10]} {ip_layer_inst/rx/eth_header_data[9]} {ip_layer_inst/rx/eth_header_data[8]} {ip_layer_inst/rx/eth_header_data[7]} {ip_layer_inst/rx/eth_header_data[6]} {ip_layer_inst/rx/eth_header_data[5]} {ip_layer_inst/rx/eth_header_data[4]} {ip_layer_inst/rx/eth_header_data[3]} {ip_layer_inst/rx/eth_header_data[2]} {ip_layer_inst/rx/eth_header_data[1]} {ip_layer_inst/rx/eth_header_data[0]}]]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {ip_layer_inst/rx/nextstate[0]} {ip_layer_inst/rx/nextstate[1]} {ip_layer_inst/rx/nextstate[2]} {ip_layer_inst/rx/nextstate[3]} {ip_layer_inst/rx/nextstate[4]} {ip_layer_inst/rx/nextstate[5]} {ip_layer_inst/rx/nextstate[6]} {ip_layer_inst/rx/nextstate[7]}]]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {ip_layer_inst/rx/state[0]} {ip_layer_inst/rx/state[1]} {ip_layer_inst/rx/state[2]} {ip_layer_inst/rx/state[3]} {ip_layer_inst/rx/state[4]} {ip_layer_inst/rx/state[5]} {ip_layer_inst/rx/state[6]} {ip_layer_inst/rx/state[7]}]]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {ip_layer_inst/rx/state_counter[0]} {ip_layer_inst/rx/state_counter[1]} {ip_layer_inst/rx/state_counter[2]} {ip_layer_inst/rx/state_counter[3]} {ip_layer_inst/rx/state_counter[4]} {ip_layer_inst/rx/state_counter[5]} {ip_layer_inst/rx/state_counter[6]} {ip_layer_inst/rx/state_counter[7]} {ip_layer_inst/rx/state_counter[8]} {ip_layer_inst/rx/state_counter[9]} {ip_layer_inst/rx/state_counter[10]} {ip_layer_inst/rx/state_counter[11]} {ip_layer_inst/rx/state_counter[12]} {ip_layer_inst/rx/state_counter[13]} {ip_layer_inst/rx/state_counter[14]} {ip_layer_inst/rx/state_counter[15]}]]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {ip_layer_inst/rx/udp_header_data[63]} {ip_layer_inst/rx/udp_header_data[62]} {ip_layer_inst/rx/udp_header_data[61]} {ip_layer_inst/rx/udp_header_data[60]} {ip_layer_inst/rx/udp_header_data[59]} {ip_layer_inst/rx/udp_header_data[58]} {ip_layer_inst/rx/udp_header_data[57]} {ip_layer_inst/rx/udp_header_data[56]} {ip_layer_inst/rx/udp_header_data[55]} {ip_layer_inst/rx/udp_header_data[54]} {ip_layer_inst/rx/udp_header_data[53]} {ip_layer_inst/rx/udp_header_data[52]} {ip_layer_inst/rx/udp_header_data[51]} {ip_layer_inst/rx/udp_header_data[50]} {ip_layer_inst/rx/udp_header_data[49]} {ip_layer_inst/rx/udp_header_data[48]} {ip_layer_inst/rx/udp_header_data[47]} {ip_layer_inst/rx/udp_header_data[46]} {ip_layer_inst/rx/udp_header_data[45]} {ip_layer_inst/rx/udp_header_data[44]} {ip_layer_inst/rx/udp_header_data[43]} {ip_layer_inst/rx/udp_header_data[42]} {ip_layer_inst/rx/udp_header_data[41]} {ip_layer_inst/rx/udp_header_data[40]} {ip_layer_inst/rx/udp_header_data[39]} {ip_layer_inst/rx/udp_header_data[38]} {ip_layer_inst/rx/udp_header_data[37]} {ip_layer_inst/rx/udp_header_data[36]} {ip_layer_inst/rx/udp_header_data[35]} {ip_layer_inst/rx/udp_header_data[34]} {ip_layer_inst/rx/udp_header_data[33]} {ip_layer_inst/rx/udp_header_data[32]} {ip_layer_inst/rx/udp_header_data[31]} {ip_layer_inst/rx/udp_header_data[30]} {ip_layer_inst/rx/udp_header_data[29]} {ip_layer_inst/rx/udp_header_data[28]} {ip_layer_inst/rx/udp_header_data[27]} {ip_layer_inst/rx/udp_header_data[26]} {ip_layer_inst/rx/udp_header_data[25]} {ip_layer_inst/rx/udp_header_data[24]} {ip_layer_inst/rx/udp_header_data[23]} {ip_layer_inst/rx/udp_header_data[22]} {ip_layer_inst/rx/udp_header_data[21]} {ip_layer_inst/rx/udp_header_data[20]} {ip_layer_inst/rx/udp_header_data[19]} {ip_layer_inst/rx/udp_header_data[18]} {ip_layer_inst/rx/udp_header_data[17]} {ip_layer_inst/rx/udp_header_data[16]} {ip_layer_inst/rx/udp_header_data[15]} {ip_layer_inst/rx/udp_header_data[14]} {ip_layer_inst/rx/udp_header_data[13]} {ip_layer_inst/rx/udp_header_data[12]} {ip_layer_inst/rx/udp_header_data[11]} {ip_layer_inst/rx/udp_header_data[10]} {ip_layer_inst/rx/udp_header_data[9]} {ip_layer_inst/rx/udp_header_data[8]} {ip_layer_inst/rx/udp_header_data[7]} {ip_layer_inst/rx/udp_header_data[6]} {ip_layer_inst/rx/udp_header_data[5]} {ip_layer_inst/rx/udp_header_data[4]} {ip_layer_inst/rx/udp_header_data[3]} {ip_layer_inst/rx/udp_header_data[2]} {ip_layer_inst/rx/udp_header_data[1]} {ip_layer_inst/rx/udp_header_data[0]}]]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {ip_layer_inst/tx/nextstate[0]} {ip_layer_inst/tx/nextstate[1]} {ip_layer_inst/tx/nextstate[2]} {ip_layer_inst/tx/nextstate[3]} {ip_layer_inst/tx/nextstate[4]} {ip_layer_inst/tx/nextstate[5]} {ip_layer_inst/tx/nextstate[6]} {ip_layer_inst/tx/nextstate[7]}]]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {ip_layer_inst/tx/state[0]} {ip_layer_inst/tx/state[1]} {ip_layer_inst/tx/state[2]} {ip_layer_inst/tx/state[3]} {ip_layer_inst/tx/state[4]} {ip_layer_inst/tx/state[5]} {ip_layer_inst/tx/state[6]} {ip_layer_inst/tx/state[7]}]]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {ip_address_from_rx[31]} {ip_address_from_rx[30]} {ip_address_from_rx[29]} {ip_address_from_rx[28]} {ip_address_from_rx[27]} {ip_address_from_rx[26]} {ip_address_from_rx[25]} {ip_address_from_rx[24]} {ip_address_from_rx[23]} {ip_address_from_rx[22]} {ip_address_from_rx[21]} {ip_address_from_rx[20]} {ip_address_from_rx[19]} {ip_address_from_rx[18]} {ip_address_from_rx[17]} {ip_address_from_rx[16]} {ip_address_from_rx[15]} {ip_address_from_rx[14]} {ip_address_from_rx[13]} {ip_address_from_rx[12]} {ip_address_from_rx[11]} {ip_address_from_rx[10]} {ip_address_from_rx[9]} {ip_address_from_rx[8]} {ip_address_from_rx[7]} {ip_address_from_rx[6]} {ip_address_from_rx[5]} {ip_address_from_rx[4]} {ip_address_from_rx[3]} {ip_address_from_rx[2]} {ip_address_from_rx[1]} {ip_address_from_rx[0]}]]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 48 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {mac_address_from_rx[47]} {mac_address_from_rx[46]} {mac_address_from_rx[45]} {mac_address_from_rx[44]} {mac_address_from_rx[43]} {mac_address_from_rx[42]} {mac_address_from_rx[41]} {mac_address_from_rx[40]} {mac_address_from_rx[39]} {mac_address_from_rx[38]} {mac_address_from_rx[37]} {mac_address_from_rx[36]} {mac_address_from_rx[35]} {mac_address_from_rx[34]} {mac_address_from_rx[33]} {mac_address_from_rx[32]} {mac_address_from_rx[31]} {mac_address_from_rx[30]} {mac_address_from_rx[29]} {mac_address_from_rx[28]} {mac_address_from_rx[27]} {mac_address_from_rx[26]} {mac_address_from_rx[25]} {mac_address_from_rx[24]} {mac_address_from_rx[23]} {mac_address_from_rx[22]} {mac_address_from_rx[21]} {mac_address_from_rx[20]} {mac_address_from_rx[19]} {mac_address_from_rx[18]} {mac_address_from_rx[17]} {mac_address_from_rx[16]} {mac_address_from_rx[15]} {mac_address_from_rx[14]} {mac_address_from_rx[13]} {mac_address_from_rx[12]} {mac_address_from_rx[11]} {mac_address_from_rx[10]} {mac_address_from_rx[9]} {mac_address_from_rx[8]} {mac_address_from_rx[7]} {mac_address_from_rx[6]} {mac_address_from_rx[5]} {mac_address_from_rx[4]} {mac_address_from_rx[3]} {mac_address_from_rx[2]} {mac_address_from_rx[1]} {mac_address_from_rx[0]}]]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {recipient_message_to_tx[9]} {recipient_message_to_tx[8]} {recipient_message_to_tx[7]} {recipient_message_to_tx[6]} {recipient_message_to_tx[5]} {recipient_message_to_tx[4]} {recipient_message_to_tx[3]} {recipient_message_to_tx[2]} {recipient_message_to_tx[1]} {recipient_message_to_tx[0]}]]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {rx_axis_fifo_tdata[0]} {rx_axis_fifo_tdata[1]} {rx_axis_fifo_tdata[2]} {rx_axis_fifo_tdata[3]} {rx_axis_fifo_tdata[4]} {rx_axis_fifo_tdata[5]} {rx_axis_fifo_tdata[6]} {rx_axis_fifo_tdata[7]}]]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {tx_axis_fifo_tdata[0]} {tx_axis_fifo_tdata[1]} {tx_axis_fifo_tdata[2]} {tx_axis_fifo_tdata[3]} {tx_axis_fifo_tdata[4]} {tx_axis_fifo_tdata[5]} {tx_axis_fifo_tdata[6]} {tx_axis_fifo_tdata[7]}]]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {udp_port_from_rx[15]} {udp_port_from_rx[14]} {udp_port_from_rx[13]} {udp_port_from_rx[12]} {udp_port_from_rx[11]} {udp_port_from_rx[10]} {udp_port_from_rx[9]} {udp_port_from_rx[8]} {udp_port_from_rx[7]} {udp_port_from_rx[6]} {udp_port_from_rx[5]} {udp_port_from_rx[4]} {udp_port_from_rx[3]} {udp_port_from_rx[2]} {udp_port_from_rx[1]} {udp_port_from_rx[0]}]]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list ip_layer_inst/rx/data_frame_enable]]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list ip_layer_inst/rx/eth_header_enable]]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list frame_ready_from_rx]]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list ip_layer_inst/rx/ip_header_enable]]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list ready_for_send_to_tx]]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list rx_axis_fifo_tlast]]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list rx_axis_fifo_tvalid]]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list start_ip_txn_to_tx]]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list ip_layer_inst/rx/state_counter_enable]]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list ip_layer_inst/rx/state_counter_reset]]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list tx_axis_fifo_tlast]]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list tx_axis_fifo_tready]]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list tx_axis_fifo_tvalid]]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list ip_layer_inst/rx/udp_header_enable]]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list clocking_wizard/inst/clk_out2]]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {mii_rxd[0]} {mii_rxd[1]} {mii_rxd[2]} {mii_rxd[3]}]]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list {phy2rmii_rxd_IBUF[0]} {phy2rmii_rxd_IBUF[1]}]]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_2 ila
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/clk [get_nets [list trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i/inst/mii_interface/mii_tx_clk_0]]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_2/probe0]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe0 [get_nets [list {mii_txd[0]} {mii_txd[1]} {mii_txd[2]} {mii_txd[3]}]]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe1 [get_nets [list mii_tx_en]]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_2 probe
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2/probe2 [get_nets [list mii_tx_er]]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets sys_clk_IBUF]
