# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/Mult_Add_NC/Mult_Add_NC.xci
# IP: The module: 'Mult_Add_NC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/Mult_Add_NC/Mult_Add_NC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mult_Add_NC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/Mult_Add_NC/Mult_Add_NC.xci
# IP: The module: 'Mult_Add_NC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.srcs/sources_1/ip/Mult_Add_NC/Mult_Add_NC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mult_Add_NC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
