# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andrew/infernet/accelerator/MNIST_Solver/MNIST_Solver.srcs/sources_1/ip/Conv_1_BRAM/Conv_1_BRAM.xci
# IP: The module: 'Conv_1_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/infernet/accelerator/MNIST_Solver/MNIST_Solver.srcs/sources_1/ip/Conv_1_BRAM/Conv_1_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conv_1_BRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/andrew/infernet/accelerator/MNIST_Solver/MNIST_Solver.srcs/sources_1/ip/Conv_1_BRAM/Conv_1_BRAM.xci
# IP: The module: 'Conv_1_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/infernet/accelerator/MNIST_Solver/MNIST_Solver.srcs/sources_1/ip/Conv_1_BRAM/Conv_1_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conv_1_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
