# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/main.xdc

# IP: ip/Mult_Add_Global_Average/Mult_Add_Global_Average.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mult_Add_Global_Average || ORIG_REF_NAME==Mult_Add_Global_Average} -quiet] -quiet
