# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andrew/infernet/misc/XOR_NN/XOR_NN.srcs/sources_1/ip/Mult_Add_COL/Mult_Add_COL.xci
# IP: The module: 'Mult_Add_COL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/infernet/misc/XOR_NN/XOR_NN.srcs/sources_1/ip/Mult_Add_COL/Mult_Add_COL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mult_Add_COL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/andrew/infernet/misc/XOR_NN/XOR_NN.srcs/sources_1/ip/Mult_Add_COL/Mult_Add_COL.xci
# IP: The module: 'Mult_Add_COL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/infernet/misc/XOR_NN/XOR_NN.srcs/sources_1/ip/Mult_Add_COL/Mult_Add_COL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mult_Add_COL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
