webtalk_init -webtalk_dir /home/andrew/infernet/accelerator/MNIST_Solver/MNIST_Solver.sim/sim_1/behav/xsim/xsim.dir/Conv_1_Channel_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 15 17:19:53 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ce86f4ad-4efe-42f3-bebd-7b2ad41a51dc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f121a475fec14a31b9530a7d3d2796fb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "86" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 10 (buster)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3391.731 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1254900 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115964_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3352851645 -regid "" -xml /home/andrew/infernet/accelerator/MNIST_Solver/MNIST_Solver.sim/sim_1/behav/xsim/xsim.dir/Conv_1_Channel_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/andrew/infernet/accelerator/MNIST_Solver/MNIST_Solver.sim/sim_1/behav/xsim/xsim.dir/Conv_1_Channel_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/andrew/infernet/accelerator/MNIST_Solver/MNIST_Solver.sim/sim_1/behav/xsim/xsim.dir/Conv_1_Channel_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
