#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Mar 28 17:26:00 EDT 2021
# SW Build 2489853 on Tue Mar 26 04:18:30 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim ip_nn_integ_tb_behav -key {Behavioral:sim_1:Functional:ip_nn_integ_tb} -tclbatch ip_nn_integ_tb.tcl -view /home/quinn/ece532-project/accelerator/tri_mode_ethernet_mac_0_ex/demo_tb_behav.wcfg -log simulate.log
