create_clock -period 8.000 -name clock -waveform {0.000 4.000} [get_ports clock]
set_property PACKAGE_PIN E3 [get_ports clock]
set_property PACKAGE_PIN C12 [get_ports reset_n]
set_property PACKAGE_PIN J15 [get_ports x]
set_property PACKAGE_PIN L16 [get_ports y]
set_property PACKAGE_PIN H17 [get_ports out]
set_property IOSTANDARD LVCMOS18 [get_ports out]
set_property IOSTANDARD LVCMOS18 [get_ports x]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
